version: '2'
services:
  php:
    build: ./
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
   
  db:
    image: mysql:8.0.22
    volumes:
      - /var/lib/mysql
      - ./docker/mysql/config.cnf:/etc/mysql/conf.d/config.cnf
    ports:
      - 3306:3306 
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: project_pabo
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
  mya:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8800:80"